### ISSUE TITLE
Change how timers are displayed on the timerboard

### ISSUE THREAD

**Issue by falcons52** [bravecollective/timerboard#10]
falcons52 commented 27 days ago
Would also like to request that the "About 3 hours from now" be changed to "3 hours and 27 minutes from now"

kiu commented 18 hours ago
AFAIK timers are relative. @falcons52 please open a separate issue for your feedback.

**Comment by mglinski** [comment]
Time displays have been updated to also include a "relative time that adjusts per a users timezone" and a shorter "timeago" format.
