### ISSUE TITLE
Offensive/Defensive Timer color coding for colorblind people

### ISSUE THREAD

**Issue by write-only** [bravecollective/timerboard#11]
Right now it's a bit hard to discern between offensive and defensive timers for me (red/green colorblind).

Would be nice if there was also an icon or some other visual hint for timer category instead of just color.

**Comment by ccatlett1984** [comment]
Shield vs sword would work.

**Comment by mglinski** [comment]
Added this in real quick, had a few requests for it. Feel free to comment on the icon choice, or link me to other better icon sets. I would prefer to use the glyphicon set thats included in bootstrap, but there no shield or sword icons in there.

**Comment by mglinski** [comment]
Production is updated with the new icons.

**Comment by write-only** [comment]
Thanks for your fast response! The more saturated color around the the icons makes it a lot better to see for me. As for the icon choice there's not really anything better in glyphicons to use I think.

**Comment by mglinski** [comment]
I changed the color and position of the icons to not confuse (hopefully) and added a browser TZ based conversion for when timers are actually happening.
