### ISSUE TITLE
Timerboard UI Improvements

### ISSUE THREAD

**Issue by cordeliaclopton** [bravecollective/timerboard#12]
Yesterday's CNM Meeting notes indicated a desire to improve the UI of the timerboard. What, specifically, needs to be done?

**Comment by mglinski** [comment]
I mostly made the changes that were requested in the meeting.

The last thing that was requested and is not implemented, is an importance index (Think DEFCON, 5-1)

The changes that I made were adding the user who reported the timer into the timer detail page, and show the region, const info for a timer to help identify timers across regions.
