### ISSUE TITLE
Error when re-logging on an expired session?

### ISSUE THREAD

**Issue by kaishek** [bravecollective/timerboard#6]
After leaving cron.braveineve.com open, refreshing, then re-logging get the error page: http://pastebin.com/9n7Xu7P1

Possibly from catch block in `ApiUserProvider::retrieveByCredentials`?

Error is cleared by deleting cron.braveineve.com cookies and logging again.

**Comment by mglinski** [comment]
Error is a known, long outstanding issue in Core.
